### ISSUE TITLE
关于FTP命令小写问题

### ISSUE THREAD

**Issue by laijinrong31** [yangziwen/zy-ftp#1]
我使用您的ftp用作海康大华摄像头ftp的插件。发现大华摄像头上传文件失败，貌似主要原因是大华摄像头的命令是小写，您再CommandFactory.class 有做过转换，但是OtherState.class 中request.getCommand() 没有做大小写处理导致了类型转换失败从而再UploadFileInfo中 第32行被return，导致上传失败。看下是否有这样的问题呢？

**Comment by yangziwen** [comment]
多谢关注哈，我会尽快看下这个问题。是否可以留下联系方式，我们具体沟通下？

**Comment by yangziwen** [comment]
已在FtpRequest的构造方法处添加了toUpperCase的处理，可以使用最新版本的代码再验证下~

**Comment by laijinrong31** [comment]
> 已在FtpRequest的构造方法处添加了toUpperCase的处理，可以使用最新版本的代码再验证下~

验证了是可以的，还看到了你解决内存泄漏的问题，之前测试上传 大文件的时候确实会崩，现在也测试可以了

**Comment by laijinrong31** [comment]
感谢
